### PR TITLE
added link to codemonk

### PR DESCRIPTION
**Pull request by himanshusanecha**
codemonk is an hackerearth initiation that provides CP questions topic wise covering every data structure and algorithms

### CODE REVIEW

**Comment by thepushkarp** [comment]
Thanks for adding this!
Take some more time and see if you can find a couple more interesting resources to add here. Then we'll merge them all under this PR.

**Comment by himanshusanecha** [comment]
for sure sir !

**Review by theyashshahs — APPROVED** [review]

**Comment by theyashshahs** [comment]
@himanshusanecha do you have more resources to add to this repo

**Comment by himanshusanecha** [comment]
no sir all the other resources are already present if i would find some links to free courses i would add them as soon as possible
Thank you

**Comment by thepushkarp** [comment]
Cool! Merging this then.

**Pull request merged**
